
service: ${file(./configs/serverless.yml):service}

frameworkVersion: '3'

package: ${file(./configs/serverless.yml):package}

provider: ${file(./configs/serverless.yml):provider}

functions: ${file(./configs/functions.yml):functions}

custom:
  serverless-offline:
    httpPort: 3000
plugins:
  - serverless-offline

  
