
functions:

  auth:
    handler: src/function/Auth/verifyToken.verifyToken

  createUser:
    handler: src/function/Users/create_user.createUser
    events:
      - http:
          path: /create-user
          method: post
          cors: true
  uploadFileAvatar:
    handler: src/function/Users/upload.uploadFileAvatar
    events:
      - http:
          path: /upload-file
          method: put
          cors: true

